# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main"]
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: pkg build
        working-directory: ./src/building-blocks
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: identity_service build
        working-directory: ./src/identity
      - run: npm ci
      - run: npm run build --if-present

      - name: identity_service test
        working-directory: ./src/identity
      - run: npm test

