name: CI

on:
  push:
    branches: [ "main"]
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: pkg build
      - run: npm install
        working-directory: ./src/building-blocks
      - run: npm run build
        working-directory: ./src/building-blocks

      - name: identity_service build
      - run: npm install
        working-directory: ./src/identityd
      - run: npm run build
        working-directory: ./src/identityd

      - name: identity_service test
      - run: npm test
        working-directory: ./src/identity


